name: Publish to RubyGems
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - run: bundle install
    - run: bundle exec rake build
    - name: Export RubyGems Credentials
      run: |
        CRED=~/.gem/credentials
        mkdir -p ~/.gem
        echo "---" > $CRED
        echo ":rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}" >> $CRED
        chmod 0600 $CRED
    - name: Push gem
      run: |
        VERSION=$(bundle exec rake print_version)
        TAG_NAME=${{ github.event.release.tag_name }}
        if [ "v${VERSION}" != $TAG_NAME ]; then
          echo "Ref ${TAG_NAME} not match with v${VERSION}"
          exit 1
        fi
    - run: gem push "pkg/middleman-ogp-${VERSION}.gem"
